[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_16", "tini"]

[phases.install]
cmds = [
  "cd /app/web && npm ci",
  "cd /app/bff && npm ci"
]

[phases.build]
cmds = [
  "cd /app/web && npm run build",
  "cd /app/bff && npm run build"
]

[start]
cmd = "node bff/dist/server.js"
