[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_16", "tini"]

[phases.install]
cmds = [
  "npm install --global n && \"$(npm prefix --global)/bin/n\" 20.11.1",
  "cd /app/web && /usr/local/n/versions/node/20.11.1/bin/npm ci",
  "cd /app/bff && /usr/local/n/versions/node/20.11.1/bin/npm ci"
]

[phases.build]
cmds = [
  "cd /app/web && /usr/local/n/versions/node/20.11.1/bin/npm run build",
  "cd /app/bff && /usr/local/n/versions/node/20.11.1/bin/npm run build"
]

[start]
cmd = "/usr/local/n/versions/node/20.11.1/bin/node bff/dist/server.js"
