[phases.setup]
nixPkgs = ["nodejs_20", "postgresql_16", "tini"]

[phases.install]
cmds = [
  "npm install --global n && n 20.11.1",
  "PATH=/usr/local/bin:$PATH cd /app/web && PATH=/usr/local/bin:$PATH npm ci",
  "PATH=/usr/local/bin:$PATH cd /app/bff && PATH=/usr/local/bin:$PATH npm ci"
]

[phases.build]
cmds = [
  "PATH=/usr/local/bin:$PATH cd /app/web && PATH=/usr/local/bin:$PATH npm run build",
  "PATH=/usr/local/bin:$PATH cd /app/bff && PATH=/usr/local/bin:$PATH npm run build"
]

[start]
cmd = "PATH=/usr/local/bin:$PATH node bff/dist/server.js"
